# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7769dfdbdf33dad0f4057d8052ac1c88dcb7a9445ff096fda2af6eb889032c056ae7aaec68939375dfd57f20add49408c0346805c6f834de1c0fe66c74c19369

test:
  secret_key_base: d9509db85e39385cfccf741cdaaed0143b490f363c6f2813662d0623d56462040e46d0c156ebe963adad3525823d17985e69561dd17fb35f499c1f8f3c16cfd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
